# Site settings
title: Madhu Sudhan
twitter_username: madroidpro
name: Madhu Sudhan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/madroid/
 - title: GitHub
   url: https://github.com/madroidpro
 - title: Twitter
   url: https://twitter.com/madroidpro

#Any buzzword skills you want to include
skills:
 - Microservices
 - Spring Boot
 - Java
 - REST
 - Android
 - Kotlin


#Work experience is required
roles:
 - title: Senior Engineer
   start: 2017
   end: Ongoing
   employer: Robert Bosch Engineering and Innovation
   description: I am a senior engineer working across the full-stack, I am involved in all aspects of the technology including the Mobile app (Android) development and back-end services.
 - title: Software Developer
   start: 2015
   end: 2017
   employer: Infovita Technologies pvt ltd
   description: Infovita Technologies was a startup mainly working on medical software domain, I was involved in all aspects of the technology including the Mobile app (Android) development and back-end services aswell as managing a team of six.
 - title: Software Developer
   start: 2013
   end: 2015
   employer: Nervecentrex Softwares
   description: I was involved in developing Mobile app (Android) development.


#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date: 2013
   subject: Computer Science and Engineering
   school: Vishveshwarayya Technological University (VTU)


#List of interesting Github repo/projects to include - optional
github:
 - madroidpro/BT_AutoConnect
 - madroidpro/ChillaaxCaptain

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/258813/rhinds
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am an engineer with 8 years experience working in technology. I have  have worked across a broad range of technologies thereon: Java, Kotlin, Android, As well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of javascript technologies over the years, through jQuery, React. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code <br/><br/>

