# Site settings
title: Madhu Sudhan
twitter_username: madroidpro
name: Madhu Sudhan Henchinapalya Nagaraj

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/madroid/
 - title: GitHub
   url: https://github.com/madroidpro
 - title: Twitter
   url: https://twitter.com/madroidpro

#Any buzzword skills you want to include
skills:
 - Java
 - Kotlin
 - Spring Boot
 - React

#Work experience is required
roles:
 - title: Senior Engineer
   start: 2017
   end: Ongoing
   employer: Robert Bosch Engineering and Innovation
   description: I am a senior engineer working across the full-stack, I am involved in all aspects of the technology including the Mobile app (Android) development and back-end services.
 

#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date: 2013
   subject: Computer Science and Engineering
   University:Vishveshwarayya Technological University (VTU)


#List of interesting Github repo/projects to include - optional
github:
 - madroidpro/BT_AutoConnect
 - madroidpro/ChillaaxCaptain
